[package]
name = "cui_command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin_img_conv = { path = "../bin_img_conv" }
mimalloc = { version = "0.1", default-features = false }
