[package]
name = "bin_img_conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17"
image = "0.24"
rand = "0.8"
dashu = "0.3"
num-traits = "0.2"
lzma-rs = "0.3"